### ISSUE TITLE
why don't you just read the existing bp.json files?

### ISSUE THREAD

**Issue by oviwankenobi** [consenlabs/eos-bp-profile#236]
hi
if you really want to help current BPs already have a bp.json uploaded to their sites
e.g. EOS Romania has it here
http://eos.romania22.com/bp.json

each BPs have their bp.json loaded on their websites
so why don't you just use those?

thank you

**Comment by makoshan** [comment]
We have considered this part of standard before, but because of our own business considerations, we have used our own specification.
